---
development:
  dialect: postgres
  database: buffalo_book
  user: postgres
  password: adi
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:adi@127.0.0.1:5432/buffalo_book_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:adi@127.0.0.1:5432/buffalo_book_production?sslmode=disable"}}
